Repository XFox111/PasswordGeneratorExtension, pull requests merged in 2022-12, with the labels that each got.

#70 Lang PT-BR
  README.md
  public/_locales/pt_BR/messages.json
Labels: enhancement, locale

#79 Minor 2.1.0
  package.json
  yarn.lock
Labels: security fix, dependencies, patch-tuesday, locale

#87 Fixed tooltip trigger area #81
  src/Components/SettingsSection.tsx
Labels: bug, help wanted

#88 PT-BR translation correction
  public/_locales/pt_BR/messages.json
Labels: locale

#89 Let it snow!
  src/App.scss
  src/App.tsx
  src/Holidays/Snow.scss
  src/Holidays/Snow.tsx
Labels: enhancement

#90 Minor 2.2.0
  package.json
  public/_locales/pt_BR/messages.json
  src/App.scss
  src/App.tsx
  src/Components/SettingsSection.tsx
  src/Holidays/Snow.scss
  src/Holidays/Snow.tsx
  yarn.lock
Labels: enhancement, dependencies, patch-tuesday, bugfix
