Repository XFox111/PasswordGeneratorExtension, pull requests merged in 2022-10, with the labels that each got.

#26 Patch 2.0.1
  .github/workflows/pr_pipeline.yaml
  package.json
  yarn.lock
Labels: dependencies

#52 Fix for issue #51 - Extension is not working on firefox
  package.json
  src/Components/SettingsSection.tsx
  src/Services/BackgroundService.ts
  src/Services/ContentService.ts
  src/Utils/Browser.ts
  src/Utils/GeneratorOptions.ts
  src/Utils/Localization.ts
  src/Utils/Settings.ts
  yarn.lock
Labels: bug, enhancement

#53 Patch 2.0.2
  .github/workflows/cd_pipeline.yaml
  .github/workflows/pr_pipeline.yaml
  CONTRIBUTING.md
  craco.config.ts
  package.json
  public/_locales/en/messages.json
  public/_locales/pl/messages.json
  public/_locales/ru/messages.json
  public/_locales/uk/messages.json
  public/index.html
  public/manifest.json
  public/manifest.v2.json
  src/App.scss
  src/Assets/BuyMeACoffee.svg
  src/Components/AboutSection.tsx
  src/Components/CharacterHelpDialog.tsx
  src/Components/PasswordView.tsx
  src/Components/SettingsSection.tsx
  src/Services/BackgroundService.ts
  src/Services/ContentService.ts
  src/Utils/Browser.ts
  src/Utils/Generator.ts
  src/Utils/GeneratorOptions.ts
  src/Utils/Localization.ts
  src/Utils/Settings.ts
  tsconfig.json
  yarn.lock
Labels: bug, documentation, enhancement, dependencies
