Repository XFox111/PasswordGeneratorExtension, pull requests merged in 2023-11, with the labels that each got.

#231 Zero-day patch: Batch 1
  .github/workflows/pr_next.yaml
  package.json
  yarn.lock
Labels: dependencies

#236 Zero-day patch: Batch 2
  package.json
  yarn.lock
Labels: dependencies

#238 Zero-day patch: Batch 3
  .github/workflows/pr_next.yaml
  yarn.lock
Labels: security fix, dependencies, github_actions

#240 Fix for CD workflow
  .github/workflows/cd_pipeline.yaml
Labels: github_actions

#243 Fix Bug: The link to source code is redirecting to a 404 page
  src/Data/Links.ts
Labels: bug
